"""Prompts module."""

from .system_prompts import (
    ROUTER_PROMPT,
    BUG_DETECTOR_PROMPT,
    SECURITY_ANALYZER_PROMPT,
    PERFORMANCE_REVIEWER_PROMPT,
    QUALITY_CHECKER_PROMPT,
    AGGREGATOR_PROMPT
)

__all__ = [
    "ROUTER_PROMPT",
    "BUG_DETECTOR_PROMPT",
    "SECURITY_ANALYZER_PROMPT",
    "PERFORMANCE_REVIEWER_PROMPT",
    "QUALITY_CHECKER_PROMPT",
    "AGGREGATOR_PROMPT"
]
